<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Richard Barton">
<meta name="dcterms.date" content="2024-01-22">

<title>Pengaruh Ekspor Batu Bara terhadap PDB Indonesia Tahun 2000 Hingga 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Batu Bara terhadap PDB Indonesia Tahun 2000 Hingga 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Richard Barton </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 22, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia merupakan salah satu produsen batu bara terbesar di dunia dengan cadangan yang melimpah. Ekspor batu bara telah menjadi salah satu sumber pendapatan utama bagi Indonesia dan memainkan peran penting dalam pertumbuhan ekonomi negara. Perlu diketahui bahwa Batu bara merupakan sumber daya energi utama di Indonesia dan telah digunakan dalam sektor industri, pembangkit listrik, dan keperluan domestik lainnya. Konsumsi batu bara di dalam negeri dan ekspor batu bara memberikan kontribusi yang signifikan terhadap keberlanjutan sektor energi Indonesia.</p>
<p>Dari tahun 2000 hingga 2022, ekspor batu bara Indonesia mengalami perkembangan yang signifikan, dengan peningkatan volume dan nilai ekspor. Ini di buktikan berdasarkan Permintaan global terhadap batu bara, terutama dari negara-negara seperti Tiongkok dan India, yang telah menjadi faktor utama dalam meningkatnya ekspor batu bara Indonesia dan ini menyebabkan Ekspor batu bara memberikan kontribusi signifikan terhadap Produk Domestik Bruto (PDB) Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Dalam penelitian ini Peneliti menggunakan objek data yang di ambil melalui Badan Pusat Statistik ( BPS ) berupa data Ekspor batubara dan PDB. Terdapat satu variable independen berupa ekspor batubara dan satu variable dependen berupa PDB Indonesia. Penelitian ini bersifat time series dalam periode jangka waktu tahun 2000 – 2022</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li><p>Sejauh mana kontribusi ekspor batu bara terhadap pertumbuhan PDB Indonesia dari tahun 2000 hingga 2022, dan bagaimana pola pertumbuhan ini berkaitan dengan fluktuasi harga batu bara di pasar internasional?</p></li>
<li><p>Bagaimana perkembangan permintaan global terhadap batu bara, khususnya dari pasar utama seperti Tiongkok dan India, mempengaruhi volume ekspor batu bara Indonesia dan kontribusinya terhadap PDB?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini ialah untuk Menilai sejauh mana ekspor batu bara berkontribusi terhadap pertumbuhan Produk Domestik Bruto (PDB) Indonesia dari tahun 2000 hingga 2022 serta Menganalisis faktor-faktor eksternal dan internal yang memengaruhi volume dan nilai ekspor batu bara, seperti permintaan global, harga pasar internasional, dan kebijakan pemerintah.</p>
<p>Manfaat penelitian ini ialah Membantu dalam perencanaan pengelolaan sumber daya ekonomi negara dengan memahami sejauh mana ekspor batu bara dapat menjadi penyumbang penting terhadap pendapatan nasional. Serta Menambah literatur dan pengetahuan terkait dampak ekspor batu bara terhadap PDB Indonesia, memberikan kontribusi pada penelitian ekonomi dan kebijakan energi.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Ekspor batu bara Indonesia pada 2022 mencapai 360,28 juta ton, tumbuh 4,29% dibanding 2021. Nilai ekspornya mencapai USD 46,74 miliar, naik 76,16% dibanding 2021 sekaligus menjadi rekor tertinggi dalam dua dekade terakhir. Kenaikan nilai ekspor batu bara Indonesia dipengaruhi oleh lonjakan harga komoditas global, terutama akibat perang Rusia-Ukraina dan konflik politik antara Rusia-Uni Eropa yang memicu krisis energi di sebagian wilayah Eropa. Hal ini membuat Ekspor batu bara Indonesia memberikan kontribusi sebesar 4,5% terhadap total PDB Indonesia pada kuartal I/2022, meski ekspor komoditas tersebut sempat dilarang oleh pemerintah pada awal tahun. Yang membuat Pertumbuhan ekonomi Indonesia pada kuartal I/2022 sebesar 5,01% yoy, didorong oleh kinerja ekspor yang tumbuh 16,22% yoy2.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 34%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>tahun</th>
<th>Eks. batubara(juta ton)</th>
<th>PDB(miliar USD)</th>
<th>X</th>
<th>Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2000</td>
<td>62.3</td>
<td>165.3</td>
<td>1.794488047</td>
<td>2.218272854</td>
</tr>
<tr class="even">
<td>2001</td>
<td>72.8</td>
<td>173.7</td>
<td>1.862131379</td>
<td>2.239799818</td>
</tr>
<tr class="odd">
<td>2002</td>
<td>81.1</td>
<td>193.6</td>
<td>1.909020854</td>
<td>2.286905353</td>
</tr>
<tr class="even">
<td>2003</td>
<td>92.4</td>
<td>238.5</td>
<td>1.965671971</td>
<td>2.377488383</td>
</tr>
<tr class="odd">
<td>2004</td>
<td>114.1</td>
<td>299.4</td>
<td>2.057285644</td>
<td>2.476251796</td>
</tr>
<tr class="even">
<td>2005</td>
<td>131.6</td>
<td>364.6</td>
<td>2.119255889</td>
<td>2.561816664</td>
</tr>
<tr class="odd">
<td>2006</td>
<td>163.9</td>
<td>432.8</td>
<td>2.214578954</td>
<td>2.636287252</td>
</tr>
<tr class="even">
<td>2007</td>
<td>187.8</td>
<td>510.2</td>
<td>2.273695588</td>
<td>2.707740454</td>
</tr>
<tr class="odd">
<td>2008</td>
<td>202.8</td>
<td>550.3</td>
<td>2.307067951</td>
<td>2.740599513</td>
</tr>
<tr class="even">
<td>2009</td>
<td>230.2</td>
<td>538.8</td>
<td>2.362105319</td>
<td>2.731427587</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>275.2</td>
<td>755.8</td>
<td>2.43964843</td>
<td>2.878406888</td>
</tr>
<tr class="even">
<td>2011</td>
<td>325.6</td>
<td>893.6</td>
<td>2.512684396</td>
<td>2.95114316</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>347.5</td>
<td>918.3</td>
<td>2.540954809</td>
<td>2.962984584</td>
</tr>
<tr class="even">
<td>2013</td>
<td>381.4</td>
<td>915.9</td>
<td>2.581380689</td>
<td>2.961848059</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>356.3</td>
<td>890.8</td>
<td>2.551815822</td>
<td>2.949780208</td>
</tr>
<tr class="even">
<td>2015</td>
<td>328.4</td>
<td>861.9</td>
<td>2.516403148</td>
<td>2.935456881</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>311.3</td>
<td>932.3</td>
<td>2.493179121</td>
<td>2.969555684</td>
</tr>
<tr class="even">
<td>2017</td>
<td>319.1</td>
<td>1,015.5</td>
<td>2.503926804</td>
<td>3.006679928</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>343.1</td>
<td>1,042.2</td>
<td>2.535420718</td>
<td>3.017951069</td>
</tr>
<tr class="even">
<td>2019</td>
<td>374.9</td>
<td>1,119.2</td>
<td>2.57391544</td>
<td>3.048907701</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>341.5</td>
<td>1,088.8</td>
<td>2.533390708</td>
<td>3.036948112</td>
</tr>
<tr class="even">
<td>2021</td>
<td>345.5</td>
<td>1,074.6</td>
<td>2.538448052</td>
<td>3.031246836</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>360.1</td>
<td>1,113.5</td>
<td>2.556423121</td>
<td>3.046690221</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan pendekatan kuantitatif dengan menggunakan data sekunder berupa data ekspor batu bara, PDB Indonesia dari tahun 2000 hingga 2022. Data diperoleh dari Badan Pusat Statistik (BPS). Dan Variabel penelitian terdiri dari variabel dependen dan variabel independen. Variabel dependen adalah pertumbuhan ekonomi Indonesia yang diukur dengan PDB riil. Variabel independen adalah ekspor batu bara, konsumsi batu bara, nilai tukar, dan harga acuan batu bara Indonesia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>eksporbb<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/metopenrichart/eksporbb.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(eksporbb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  Tahun Ekspor Batu Bara       …¹ ...3  PDB INDONESIA       …² ...5      X     Y
  &lt;dbl&gt;                     &lt;dbl&gt; &lt;lgl&gt;                  &lt;dbl&gt; &lt;lgl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    NA                      NA   NA                       NA  NA    NA    NA   
2  2000                      62.3 NA                      165. NA     1.79  2.22
3  2001                      72.8 NA                      174. NA     1.86  2.24
4  2002                      81.1 NA                      194. NA     1.91  2.29
5  2003                      92.4 NA                      238. NA     1.97  2.38
6  2004                     114.  NA                      299. NA     2.06  2.48
# ℹ abbreviated names: ¹​`Ekspor Batu Bara        ( juta ton )`,
#   ²​`PDB INDONESIA          ( Milliar Dolar AS )`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>eksporbb,<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>Y))<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"pink"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan ekspor batubara dan PDB"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"ekspor batu bara"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"PDB"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik Indonesia"</span>)<span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat dengan “y” sebagai variabel independen. Penelitian ini merbaksud mencari hubungan antara Ekspor Batubara Terhadap PDB Indonesia. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDB dan <span class="math inline">\(x_t\)</span> adalah ekspor batubara.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients:</th>
<th>Estimate</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.25117</td>
<td>0.00205</td>
</tr>
<tr class="even">
<td>x</td>
<td>1.07916</td>
<td>&lt; 2e-16</td>
</tr>
</tbody>
</table>
<p>Hasil diatas dimasukkan dalam persamaan dan menghasilkan rumus persamaan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\ 0.25117 + \ 1.07916x_t+\mu_t
\]</span></p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>eksporbb<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"eksporbb.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...3`
• `` -&gt; `...5`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>eksporbb)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = eksporbb)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.075050 -0.022659  0.002885  0.029201  0.053368 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.25117    0.07140   3.518  0.00205 ** 
X            1.07916    0.03038  35.522  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.037 on 21 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.9836,    Adjusted R-squared:  0.9829 
F-statistic:  1262 on 1 and 21 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Residual standard error: 0.037 on 21 degrees of freedom (1 observation deleted due to missingness) Multiple R-squared: 0.9836, Adjusted R-squared: 0.9829 F-statistic: 1262 on 1 and 21 DF, p-value: &lt; 2.2e-1</p>
<p>Nilai Multiple R-Square sebesar 0.9836, dan F-Statistic 1262, Nilai Multiple R-Square ini menunjukkan bahwa model Regresinya hanya dapat menjelaskan 98,36% variasi y, Sedangkan sisanya dipengaruhi oleh faktor lain.</p>
<p>Nilai F-Statistik memiliki P-Value Sebesar &lt;2.2e-1 , Yang berrati model regersi signifikan pada tinglat signifikasi &lt;22%. Secara keseluruhan, analisis regresi menunjukkan bahwa ada hubungan negatif dan signifikan antara x dan y, Tetapi model regresi memiliki kualitas yang rendah dalam menjelaskan variasi y. Maka peneliti perlu menambahan variabel lain untuk meningkatkan kualitas model regresi</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Ekspor batubara memiliki pengaruh signifikan yang positif terhadap PDB Indonesia, hal in dapat terjadi karena PDB dapat dipengaruhi oleh fluktuasi harga batubara di pasar internasional. Kenaikan harga batubara dapat meningkatkan pendapatan ekspor dan, akibatnya, berkontribusi positif&nbsp;terhadap&nbsp;PDB.</p>
<p>Penting untuk diingat bahwa dampak ekspor batubara terhadap PDB tidak hanya tergantung pada volume ekspor, tetapi juga pada faktor-faktor eksternal dan kebijakan internal yang dapat memoderasi atau memperkuat dampak tersebut. Oleh karena itu, perencanaan ekonomi yang bijak dan berkelanjutan diperlukan untuk memitigasi risiko dan meningkatkan dampak positif sektor ekspor batubara&nbsp;terhadap&nbsp;PDB.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>ginting, ari mulianta. (2017). Analisis Pengaruh Ekspor Terhadap Pertumbuhan Ekonomi Indonesia. Buletin Ilmiah Litbang Perdahngan, 11(1):1. https://www.researchgate.net/publication/324348679_ANALISIS_PENGARUH_EKSPOR_TERHADAP_PERTUMBUHAN_EKONOMI_INDONESIA</p>
<p>Setiawan, A., Wibowo, A. P., &amp; Rosyid, F. A. (n.d.). ANALISIS PENGARUH EKSPOR DAN KONSUMSI BATUBARA TERHADAP PERTUMBUHANEKONOMIINDONESIA. Jurnal Teknologi Mineral Dan Batubara, Volume 16 No 2(Mei 2020), Article Mei 2020.</p>
<p>Silaban, R. (n.d.). Pengaruh Nilai Tukar dan Inflasi terhadap Ekspor Non Migas di Indonesia. Jurnal Samudera Ekonomika, vol 6 no 1 (2022). https://doi.org/10.33059/jse.v6i1.5123</p>
<p>Widyasanti, A. adininggar. (n.d.). PERDAGANGAN BEBAS REGIONAL DAN DAYA SAING EKSPOR: KASUS INDONESIA. Buletin Ekonomi Moneter Dan Perbankan, vol 13 no 1 (2010). https://doi.org/10.21098/bemp.v13i1.251</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>